name: Build

on: 
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.4'

    # don't reprocess the swaggerfile in the github action - use what's committed in the repo
    - run: touch openapi/operations.yaml

    - name: Go tests
      run: make test
    - name: Go build
      run: make crossarch
