name: Build on push to master

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.4'

    # don't reprocess the swaggerfile in the github action - use what's committed in the repo
    - run: touch openapi/operations.yaml

    - name: Go tests
      run: make test
    - name: Go build
      run: make

    - name: Archive builds
      uses: actions/upload-artifact@v1
      with:
        name: isctl
        path: build
